# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240905.1"

  config.vm.define "acroueS" do |control|
    control.vm.hostname = "acroueS"
    control.vm.network "private_network", ip: "192.168.56.110"

    control.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "acroueS"]
      # vb.gui = true
      vb.cpus = 2
      vb.memory = "2048"
    end
    control.vm.provision "shell", path: "scripts/init_server.sh"
  end

  config.vm.define "acroueSW" do |control|
    control.vm.hostname = "acroueSW"
    control.vm.network "private_network", ip: "192.168.56.111"

    control.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "acroueSW"]
      # vb.gui = true
      vb.cpus = 1
      vb.memory = "512"
    end
    control.vm.provision "shell", path: "scripts/init_agent.sh"
  end


end
